"""Add video_url to Property

Revision ID: 16954b916c40
Revises: 97501b8c1cc7
Create Date: 2026-03-05 18:31:23.214836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16954b916c40'
down_revision = '97501b8c1cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('property', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('property', schema=None) as batch_op:
    #     batch_op.drop_column('video_url')
    pass

    # ### end Alembic commands ###
