"""Add email confirmation and incoming mail settings

Revision ID: 393075827ce4
Revises: ed0b716f9a50
Create Date: 2026-03-11 21:25:36.611191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393075827ce4'
down_revision = 'ed0b716f9a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('booking', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('confirmation_code', sa.String(length=10), nullable=True))
    #    batch_op.add_column(sa.Column('is_email_confirmed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('characteristic_type', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_characteristic_type_unit_type', 'unit_type', ['unit_type_id'], ['id'])

    with op.batch_alter_table('option_type', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_option_type_unit_type', 'unit_type', ['unit_type_id'], ['id'])

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incoming_mail_server', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('incoming_mail_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('incoming_mail_login', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('incoming_mail_password', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('incoming_mail_use_ssl', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('incoming_mail_use_ssl')
        batch_op.drop_column('incoming_mail_password')
        batch_op.drop_column('incoming_mail_login')
        batch_op.drop_column('incoming_mail_port')
        batch_op.drop_column('incoming_mail_server')

    with op.batch_alter_table('option_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('characteristic_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('is_email_confirmed')
        batch_op.drop_column('confirmation_code')

    # ### end Alembic commands ###
