"""Add SMS settings

Revision ID: 75ec7a77e596
Revises: 6b58699d494c
Create Date: 2026-03-06 16:28:10.465080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ec7a77e596'
down_revision = '6b58699d494c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_api_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sms_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('sms_enabled')
        batch_op.drop_column('sms_api_id')

    # ### end Alembic commands ###
