"""Initial migration

Revision ID: 97501b8c1cc7
Revises: 
Create Date: 2026-03-05 18:19:12.988713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97501b8c1cc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('favicon_url', sa.String(length=300), nullable=True),
    sa.Column('slogan', sa.String(length=300), nullable=True),
    sa.Column('map_url', sa.Text(), nullable=True),
    sa.Column('phone_main', sa.String(length=50), nullable=True),
    sa.Column('phone_secondary', sa.String(length=50), nullable=True),
    sa.Column('email_info', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('social_vk', sa.String(length=200), nullable=True),
    sa.Column('social_telegram', sa.String(length=200), nullable=True),
    sa.Column('social_whatsapp', sa.String(length=200), nullable=True),
    sa.Column('smtp_server', sa.String(length=100), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=100), nullable=True),
    sa.Column('smtp_password', sa.String(length=100), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=True),
    sa.Column('incoming_mail_server', sa.String(length=100), nullable=True),
    sa.Column('incoming_mail_port', sa.Integer(), nullable=True),
    sa.Column('incoming_mail_login', sa.String(length=100), nullable=True),
    sa.Column('incoming_mail_password', sa.String(length=100), nullable=True),
    sa.Column('incoming_mail_use_ssl', sa.Boolean(), nullable=True),
    sa.Column('sms_api_id', sa.String(length=100), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('characteristic_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('option_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('short_description', sa.String(length=200), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('gallery_urls', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('local_video_urls', sa.Text(), nullable=True),
    sa.Column('price_per_night', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('guest_email', sa.String(length=120), nullable=False),
    sa.Column('guest_phone', sa.String(length=20), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('guests_count', sa.Integer(), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('booking_token', sa.String(length=64), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('confirmation_code', sa.String(length=10), nullable=True),
    sa.Column('is_email_confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_booking_token'), 'booking', ['booking_token'], unique=True)
    op.create_table('booking_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('option_type_id', sa.Integer(), nullable=True),
    sa.Column('option_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['option_type_id'], ['option_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_characteristic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('characteristic_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_type_id'], ['characteristic_type.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_options',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('option_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_type_id'], ['option_type.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('property_id', 'option_type_id')
    )
    op.create_table('booking_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=200), nullable=False),
    sa.Column('device_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_booking_device_booking_id'), 'booking_device', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_device_device_token_hash'), 'booking_device', ['device_token_hash'], unique=False)
    op.create_table('booking_passkey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=300), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.String(length=200), nullable=True),
    sa.Column('aaguid', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_passkey_booking_id'), 'booking_passkey', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_passkey_credential_id'), 'booking_passkey', ['credential_id'], unique=True)
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_log_booking_id'), 'notification_log', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_log_booking_id'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_booking_passkey_credential_id'), table_name='booking_passkey')
    op.drop_index(op.f('ix_booking_passkey_booking_id'), table_name='booking_passkey')
    op.drop_table('booking_passkey')
    op.drop_index(op.f('ix_booking_device_device_token_hash'), table_name='booking_device')
    op.drop_index(op.f('ix_booking_device_booking_id'), table_name='booking_device')
    op.drop_table('booking_device')
    op.drop_table('property_options')
    op.drop_table('property_characteristic')
    op.drop_table('booking_option')
    op.drop_index(op.f('ix_booking_booking_token'), table_name='booking')
    op.drop_table('booking')
    op.drop_table('property')
    op.drop_table('option_type')
    op.drop_table('characteristic_type')
    op.drop_table('user')
    op.drop_table('unit_type')
    op.drop_table('site_settings')
    op.drop_table('review')
    op.drop_table('property_type')
    op.drop_table('contact_request')
    # ### end Alembic commands ###
